version: "3.3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
